let number = 13.05;
let number2 = -5;
const output = Math.floor(number);
const output2 = Math.ceil(number);
const output3 = Math.round(number);
const absoluteNumber = Math.abs(number2); 
const random = Math.random()*10;
const randomRounded = Math.round(random); 
console.log(output, output2, output3,randomRounded, absoluteNumber)